### PR TITLE
Hot fix ws flood error + current develop

### PR DESCRIPTION
**Pull request by JettTech**
Includes:
 - Hot-fix: handle flood of WebSocket errors following a page reload
 - Hot-fix: handle unexpected holofuel transaction states instead of throw error
 - Add current user context wrapper for holofuel
 - Add current user context wrapper for hp-admin
 - Remove date headers within inbox transaction list whenever all transactions have been actioned
 - Modify grammar (ie to/from wording) in the create request/offer page 
 - Correct misspellings/typos

### CODE REVIEW

**Review by zo-el — CHANGES_REQUESTED** [review]
We need to bump the UI version to v0.11.1

**Comment by zo-el** [comment]
@robbie we need to update the package.lock file as well

**Comment by Connoropolous** [comment]
you may want #239 as well, I've isolated the bug fix part of #234 PR there.

**Comment by JettTech** [comment]
@Connoropolous - Thanks for the heads up.  The intent of this version bump is to update hp-admin with the two hot fixes asap for QA testing efforts.

I would expect to review and merge in your PRs into develop soon, as such, they would be included in the next version bump. Meanwhile, I'll bring up this conversation with the happy team.

**Review by zo-el — APPROVED** [review]

**Pull request merged**
